version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-node
    working_directory: ~/project/firestore
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npx firebase setup:emulators:firestore
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - test
